/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        // legacy tokens (used throughout existing components)
        navy:  '#0D1B2A',
        ink:   '#1A2B3C',
        gold:  '#C9A84C',
        cream: '#F7F3EC',
        mist:  '#8DA4B8',
        pass:  '#2E7D5A',
        fail:  '#A63228',
        warn:  '#C07A20',
        domain: {
          strategy: '#4A9EDB',
          culture:  '#E8904A',
          voc:      '#7BC67A',
          design:   '#C97AC9',
          metrics:  '#E8C94A',
          adoption: '#7AC9C9',
        },

        // AcademiaAI design system (dark-mode defaults)
        'surface':                  '#16130b',
        'surface-dim':              '#16130b',
        'surface-container':        '#231f17',
        'surface-container-low':    '#1f1b13',
        'surface-container-high':   '#2d2a21',
        'surface-container-highest':'#38342b',
        'surface-bright':           '#3d392f',
        'surface-variant':          '#38342b',
        'on-surface':               '#eae1d4',
        'on-surface-variant':       '#d0c5af',
        'on-background':            '#eae1d4',
        'background':               '#16130b',
        'outline':                  '#99907c',
        'outline-variant':          '#4d4635',
        'primary':                  '#f2ca50',
        'primary-container':        '#d4af37',
        'primary-fixed':            '#ffe088',
        'primary-fixed-dim':        '#e9c349',
        'on-primary':               '#3c2f00',
        'on-primary-container':     '#554300',
        'on-primary-fixed':         '#241a00',
        'secondary':                '#b4c5ff',
        'secondary-container':      '#0053db',
        'on-secondary':             '#002a78',
        'on-secondary-container':   '#cdd7ff',
        'tertiary':                 '#bfcdff',
        'tertiary-container':       '#97b0ff',
        'on-tertiary':              '#082b72',
        'error':                    '#ffb4ab',
        'error-container':          '#93000a',
        'on-error':                 '#690005',
        'inverse-surface':          '#eae1d4',
        'inverse-on-surface':       '#343027',
        'inverse-primary':          '#735c00',
        'surface-tint':             '#e9c349',
      },
      fontFamily: {
        // AcademiaAI
        'display': ['"Noto Serif"', 'serif'],
        'serif':   ['"Noto Serif"', 'serif'],
        'sans':    ['Inter', 'sans-serif'],
        'label':   ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display': ['48px', { lineHeight: '1.2', fontWeight: '700' }],
        'h1':      ['36px', { lineHeight: '1.3', fontWeight: '700' }],
        'h2':      ['30px', { lineHeight: '1.3', fontWeight: '600' }],
        'h3':      ['24px', { lineHeight: '1.4', fontWeight: '600' }],
        'body-lg': ['18px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-md': ['16px', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['14px', { lineHeight: '1.5', fontWeight: '400' }],
        'label':   ['12px', { lineHeight: '1', letterSpacing: '0.05em', fontWeight: '600' }],
      },
      borderRadius: {
        DEFAULT: '0.25rem',
        lg:      '0.5rem',
        xl:      '0.75rem',
        '2xl':   '1rem',
        full:    '9999px',
      },
      boxShadow: {
        'primary-glow': '0 0 15px rgba(242, 202, 80, 0.15)',
        'primary-btn':  '0 0 8px rgba(242, 202, 80, 0.4)',
        'gold-sm':      '0 2px 12px 0 rgba(201,168,76,0.15)',
        'gold':         '0 4px 24px 0 rgba(201,168,76,0.2)',
        'gold-lg':      '0 8px 40px 0 rgba(201,168,76,0.25)',
        'ink':          '0 8px 32px 0 rgba(13,27,42,0.6)',
      },
      transitionTimingFunction: {
        spring: 'cubic-bezier(0.34, 1.56, 0.64, 1)',
      },
    },
  },
  plugins: [],
}
